SpiNNakerManchester/SpiNNMan

.gitignore
board_test_configuration.py
c_models/reinjector/Makefile
c_models/reinjector/reinjector.c
quick_tests.py
spinnman/messages/scp/impl/scp_dpri_exit_request.py
spinnman/messages/scp/impl/scp_dpri_get_status_request.py
spinnman/messages/scp/impl/scp_dpri_get_status_response.py
spinnman/messages/scp/impl/scp_dpri_reset_counters_request.py
spinnman/messages/scp/impl/scp_dpri_set_reinjection_packet_types.py
spinnman/messages/scp/impl/scp_dpri_set_router_emergency_timeout_request.py
spinnman/messages/scp/impl/scp_dpri_set_router_timeout_request.py
spinnman/messages/scp/impl/scp_write_link_request.py
spinnman/messages/scp/scp_command.py
spinnman/messages/scp/scp_dpri_command.py
spinnman/messages/scp/scp_dpri_packet_type_flags.py
spinnman/model/core_subset.py
spinnman/model/core_subsets.py
spinnman/model/dpri_status.py
spinnman/processes/exit_dpri_process.py
spinnman/processes/read_dpri_status_process.py
spinnman/processes/reset_dpri_counters_process.py
spinnman/processes/set_dpri_packet_types_process.py
spinnman/processes/set_dpri_router_emergency_timeout_process.py
spinnman/processes/set_dpri_router_timeout_process.py
spinnman/transceiver.py
spinnman/utilities/utility_functions.py
test.cfg
unittests/test_utils.py

Adds dropped packet reinjection

Re injector

---

quick_tests.py
spinnman/transceiver.py
unittests/test_transceiver.py

Fixes issues with SpiNNakerLink functionality

Fix spinnaker links

---

quick_tests.py
spinnman/processes/get_tags_process.py
unittests/model_tests/test_iptag_model.py

Changes to reflect updates in the IPTag interface

Fix board addresses

---

.travis.yml
doc/doc_requirements.txt
doc/source/index.rst
requirements-test.txt

Fix sphinx issues in docs
incl
text in a __init__.py for a module with no other *.py code
replace type "bytestring" with type "str" as python has no formal type bytestring

Doc fixes for sphinx

---

spinnman/transceiver.py

Minor bug fix helping with multiboard - will merge with the rest

LPG multi board

---

spinnman/connections/udp_packet_connections/__init__.py
spinnman/connections/udp_packet_connections/udp_listenable_connection.py

added new listenable udp connection

---

spinnman/messages/spinnaker_boot/spinnaker_boot_messages.py

Fix boot open file

---

spinnman/transceiver.py
unittests/test_transceiver.py

supports turning on and off watch dogs dynamically. 
so far tested with the GFE data speed up stuff. I'm not stating its perfect, but it does seem to work.
Would be amazing if a test could be contrived to test this functionality.

dynamic watch dog funcitonality

---

spinnman/connections/connection_listener.py
spinnman/exceptions.py
spinnman/processes/abstract_process.py

Wild tracebacks are a problem; let's crush them where possible!

Tracebacks should be done through the logger as much as possible

---

spinnman/connections/connection_listener.py
spinnman/connections/udp_packet_connections/udp_connection.py
spinnman/processes/get_machine_process.py

Master will go red next time it builds!

fixed bare excepts

---

spinnman/connections/scp_request_pipeline.py
spinnman/constants.py
spinnman/messages/scp/abstract_messages/bmp_request.py
spinnman/messages/scp/impl/set_power.py
spinnman/transceiver.py

Some fixes that fix the operation of the spalloc server

Fix Spalloc

---

spinnman/constants.py
spinnman/messages/eieio/command_messages/__init__.py
spinnman/messages/eieio/command_messages/host_data_read_ack.py

This just adds an acknowledgement command for buffered out, to reduce the unnecessary requests.  This is needed in other modules with the same branch name.

Fix buffered out

---

spinnman/messages/scp/impl/bmp_get_version.py

- added a missing parameter in a method call.

Fpga check update

---

spinnman/connections/udp_packet_connections/bmp_connection.py

fixes a issue with bmp connections and ports

fixes issue with ports 

---

spinnman/model/cpu_infos.py

Fixes https://github.com/SpiNNakerManchester/SpiNNMan/issues/124

added items for python3 as iteritems no longer used

---

spinnman/processes/get_machine_process.py

Depends on https://github.com/SpiNNakerManchester/SpiNNMachine/pull/73

Reuse processor Object when the same

---

spinnman/model/router_diagnostics.py

Fix mask for router emergency timeout

---

spinnman/processes/get_machine_process.py

The reading of the P2P table data within `GetMachineProcess` was wrong, in that it could reorder the columns of table data. That only occurred when the reading of one column gets delayed (because of the need to resend a packet) and the reading of the column after it works immediately, allowing the results to slip past each other. This would result in them being entered into the host-side raw P2P table data array in the wrong order, which in turn would corrupt the building of the parsed P2P table.
Fortunately this is a very rare occurrence in the Python code as the language is so slow that multiple packets in flight are hardly ever launched in practice, but it is a bug that is fixed by binding where to store in the table (known at packet dispatch time!) into the response callback. …

Fix long-standing bug in SpiNNMan with packet reordering

---

board_test_configuration.py

Ping now in utils

---

spinnman/connections/udp_packet_connections/boot_connection.py
spinnman/constants.py
spinnman/messages/eieio/data_messages/eieio_data_header.py
spinnman/model/chip_info.py
spinnman/processes/get_routes_process.py
spinnman/transceiver.py
spinnman/utilities/io/memory_io.py

Bunch of fixes. Also see SpiNNakerManchester/SpiNNMachine#89

Fixes from java code review

---

setup.py
spinnman/messages/spinnaker_boot/system_variable_boot_values.py
spinnman/model/cpu_infos.py
spinnman/processes/read_iobuf_process.py
spinnman/transceiver.py

Part of https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75

Deprication Warnings

---

spinnman/processes/get_machine_process.py
spinnman/utilities/reports.py
unittests/test_transceiver.py

Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/104

Wrapped machine

---

spinnman/utilities/utility_functions.py

This function is generally useful, and can be implemented in SpiNNMan only.

Port trigger

---

spinnman/processes/get_machine_process.py
spinnman/transceiver.py

Options for handling chips that Lie about having an ip address
Depends on:https://github.com/SpiNNakerManchester/SpiNNMachine/pull/113
Adjusted with:https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/449

remove bad ethernets

---

spinnman/get_cores_in_run_state.py
spinnman/model/cpu_infos.py
spinnman/transceiver.py

states with cores

---

spinnman/transceiver.py

Adds a util function to transceiver rather than having it in several places
Can be nmerged before the PRs that depend on it.

read_user_0 function

---

setup.py
spinnman/exceptions.py
spinnman/messages/spinnaker_boot/system_variable_boot_values.py
spinnman/model/cpu_infos.py
spinnman/processes/read_iobuf_process.py
spinnman/transceiver.py

https://github.com/SpiNNakerManchester/SpiNNUtils/issues/102

fixed incorrect import from collections.abc

---

spinnman/messages/spinnaker_boot/system_variable_boot_values.py
spinnman/transceiver.py

They'd just never been tested before.

Make the code to read system variables work with arrays

---

spinnman/processes/get_machine_process.py
spinnman/transceiver.py

Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/124

Max cores per chip

---

spinnman/transceiver.py

again with the end user registers

added functionality to read user1

---

spinnman/messages/scp/impl/flood_fill_end.py
spinnman/messages/scp/impl/flood_fill_start.py

Minor change to make the Flood Fill Start and Flood Fill End NN retry match that of Flood Fill Data.  From my own testing this doesn't break anything.

Increase retry

---

spinnman/connections/udp_packet_connections/udp_connection.py

Make sure data is sent (matches SpiNNakerManchester/JavaSpiNNaker#261)

fewer timeouts

---

spinnman/processes/get_machine_process.py

cheap. easy. and shouldnt have been needed in the first place. but there we go

better log so you CAN ACTUALLY READ THE ERROR!

---

.travis.yml
setup.py
spinnman/messages/spinnaker_boot/spinnaker_boot_messages.py

Also run each version with best choice of Ubuntu distribution

Add testing with Python 3.8

---

spinnman/connections/scp_request_pipeline.py
spinnman/exceptions.py
spinnman/processes/abstract_process.py
spinnman/processes/get_machine_process.py
unittests/model_tests/test_abstract_process.py

i think this works. only error tests will tell us such

allow better error reporting with ip addresses

---

spinnman/connections/abstract_classes/connection.py
spinnman/connections/connection_listener.py
spinnman/transceiver.py
spinnman/utilities/io/abstract_io.py
spinnman/utilities/io/file_io.py
spinnman/utilities/io/memory_io.py

See https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/680

Use the AbstractContextManager from SpiNNUtils

---

.github/workflows/python_actions.yml
requirements-test.txt

Sphinx 3.3.1 works on my machine with Python 3.6

Update the sphinx version

---

spinnman/transceiver.py

Don't need the equivalent for writing a word.
Also tidied up the docs in a couple of spots nearby in passing, mostly to do with noting that the `read_*` methods can also read DTCM (and that's when giving the `cpu` parameter is useful).

Add a method for the simple case of reading one word

---

requirements-test.txt

https://github.com/SpiNNakerManchester/SpiNNUtils/pull/126

Corrections to numpy version requirements

---

spinnman/transceiver.py

wee change that will log what cores are stalling things on a cyclic basis when things slow down unexpectantly.

extra logging when things stall

---

spinnman/transceiver.py

tested by : https://github.com/SpiNNakerManchester/sPyNNaker8/pull/539

Config to shut up debug

---

requirements-test.txt

found by https://github.com/SpiNNakerManchester/PACMAN/issues/417

SpinUtils imports numpy so no need to repeat complicated here

---

spinnman/processes/read_memory_process.py
spinnman/transceiver.py

needs https://github.com/SpiNNakerManchester/SpiNNMachine/pull/168
Logs the where is info of the cores before calling SpiNNManCoresNotInStateException

log where_is_xy

---

spinnman/transceiver.py

report x y not y twice

---

spinnman/exceptions.py
spinnman/model/cpu_infos.py
spinnman/processes/read_iobuf_process.py

Like https://github.com/SpiNNakerManchester/PACMAN/pull/425
Can be done independently.

No need for "Ordered" dict

---

spinnman/spinnman.cfg
spinnman/transceiver.py

part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/933
Also removes the never used close_original_connections=False and the data for that.

changed options rarely if ever used to cfg only

---

quick_tests.py

Fix the quick_test.py so it runs.
Added a comment on how to build it.
Manually tested.
fixes: https://github.com/SpiNNakerManchester/SpiNNMan/issues/276

Quick test fix

---

spinnman/exceptions.py
spinnman/processes/abstract_process.py
spinnman/processes/get_cpu_info_process.py

Fix the stack overflow issue seen in testing

Fix stack overflow

---

spinnman/exceptions.py
spinnman/processes/abstract_multi_connection_process_connection_selector.py
spinnman/processes/abstract_process.py
spinnman/processes/get_cpu_info_process.py
spinnman/processes/get_machine_process.py
spinnman/processes/most_direct_connection_selector.py
spinnman/processes/round_robin_connection_selector.py
spinnman/transceiver.py

If we store these during machine gathering, it makes it easy to find them when things go wrong later.
Depends on Depends on SpiNNakerManchester/SpiNNMachine#173

Store v to p map

---

.pylintrc

same as https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/946

removed no-space-check

---

spinnman/get_cores_in_run_state.py
spinnman/processes/application_copy_run_process.py

Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/180
Can safely be done before

Removes code to do with Virtual Chips.

---

spinnman/connections/abstract_classes/listenable.py
spinnman/transceiver.py
unittests/test_transceiver.py

This is a task mentioned in #298 comments.

Tidying up EIEIO listener registration practices

---

spinnman/spalloc/session.py
spinnman/spalloc/spalloc_client.py

Fixes to the spalloc client to make it stop correctly.
Part of SpiNNakerManchester/JavaSpiNNaker#737 (but can be merged without that as only useful when using Java spalloc)

Spalloc server jdbc

---

quick_tests.py
setup.cfg
spinnman/board_test_configuration.cfg
spinnman/board_test_configuration.py
spinnman/get_cores_in_run_state.py
spinnman/spinnman.cfg
test.cfg
unittests/connection_tests/test_udp_connection.py
unittests/model_tests/test_iptag_model.py
unittests/test_cfg_checker.py
unittests/test_transceiver.py

Discovered by https://github.com/SpiNNakerManchester/IntegrationTests/pull/191

Remove installed

---

spinnman/spalloc/spalloc_client.py
spinnman/spalloc/spalloc_job.py

Hels to fix bug when using proxy.  See SpiNNakerManchester/SpiNNFrontEndCommon#1071

Add ability to listen to UDP directly

---

spinnman/transceiver.py

part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1078

move load_application logic to FEC

---

setup.cfg
spinnman/_version.py

Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/236

Version bump

---

spinnman/processes/get_machine_process.py

part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/244

Is config none

---

unittests/test_transceiver.py

Missed test changes from https://github.com/SpiNNakerManchester/SpiNNMan/pull/352
Note: Only testable when there is a Physical machine
which is why guthub actions missed it.
Jenkins missed it as spinn-4.cs.man.ac.uk is down

remove the with Transceiver in tests

---

spinnman/processes/get_routes_process.py

Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/225
Cherry pick from https://github.com/SpiNNakerManchester/SpiNNMan/pull/327

name optional parameters now required.

---

spinnman/get_cores_in_run_state.py
spinnman/transceiver/transceiver_factory.py

This Branch just adds Typing to the methods that create a Transceiver

Create Transceiver always returns a Transceiver

---

spinnman/connections/udp_packet_connections/bmp_connection.py
spinnman/messages/eieio/command_messages/eieio_command_message.py
spinnman/messages/scp/impl/check_ok_response.py
spinnman/messages/scp/impl/sdram_alloc.py
spinnman/processes/get_exclude_cpu_info_process.py
spinnman/processes/get_include_cpu_info_process.py
spinnman/spalloc/spalloc_client.py
spinnman/spalloc/spalloc_eieio_connection.py
spinnman/spalloc/spalloc_eieio_listener.py
spinnman/spalloc/spalloc_job.py
spinnman/spalloc/spalloc_scp_connection.py
spinnman/transceiver/base_transceiver.py
spinnman/transceiver/mockable_transceiver.py
spinnman/transceiver/transceiver.py

Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/257
Typing annotations only!

Overrides check

---

spinnman/get_cores_in_run_state.py
spinnman/processes/application_copy_run_process.py
spinnman/transceiver/base_transceiver.py

Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/246
- Removes a hard coded 18 Processors
- makes use of Chip being a (x, y)

Chip simplification

---

spinnman/messages/scp/impl/fixed_route_read.py
spinnman/processes/get_routes_process.py
spinnman/processes/load_fixed_route_routing_entry_process.py
spinnman/processes/load_routes_process.py
spinnman/processes/read_fixed_route_routing_entry_process.py
spinnman/transceiver/base_transceiver.py
spinnman/transceiver/mockable_transceiver.py
spinnman/transceiver/transceiver.py

part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/250

Single routing entry

---

spinnman/messages/sdp/sdp_header.py

Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/260

refactor get_physical_string

---

spinnman/spalloc/session.py

fixes https://github.com/SpiNNakerManchester/SpiNNMachine/pull/263

Better error incorrect server settings

---

spinnman/spinnman.cfg

part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/274
cfg settings move to where they are used.

Cfg checker

---

.github/workflows/python_actions.yml
pyproject.toml

part of https://github.com/SpiNNakerManchester/PACMAN/pull/566

Use build simple

---

spinnman_integration_tests/test_job.py

work around for https://github.com/SpiNNakerManchester/SpiNNMan/issues/414
Notice in the actions macos_latest integration tests is a s

skip on ConnectionError

---

spinnman/spalloc/session.py
spinnman/spalloc/spalloc_client.py
spinnman/spalloc/spalloc_job.py
spinnman/spalloc/spalloc_transceiver.py
spinnman/transceiver/base_transceiver.py
spinnman/transceiver/transceiver.py

Part of:
- SpiNNakerManchester/JavaSpiNNaker#1222

More spalloc rest calls

---

spinnman/processes/__init__.py
spinnman/processes/clear_routes_process.py
spinnman/processes/malloc_sdram_process.py
spinnman/processes/set_memory_process.py
spinnman/transceiver/base_transceiver.py
spinnman/transceiver/mockable_transceiver.py
spinnman/transceiver/transceiver.py

Make more things into processes, which then take less time to execute, especially from remote places!
To make use of these changes:
- SpiNNakerManchester/SpiNNFrontEndCommon#1270
- SpiNNakerManchester/sPyNNaker#1550
Tested by:
- SpiNNakerManchester/IntegrationTests#316

Use more processes

---

doc/source/conf.py
spinnman/config_setup.py
spinnman/processes/get_machine_process.py
spinnman/spinnman.cfg
unittests/.gitignore
unittests/test_cfg_checker.py

build son https://github.com/SpiNNakerManchester/SpiNNMan/pull/434
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/299

Cfg documentor

---

spinnman/exceptions.py
spinnman/spalloc/spalloc_client.py
spinnman/transceiver/base_transceiver.py

A different exception for boot errors
This makes it easier to treat there different to other io errors
Also fixes a mypy error in master

SpinnmanBootException

---

spinnman/transceiver/base_transceiver.py

Needed for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1298
SpinnmanBootException was raised in the wrong place

SpinnmanBootException in the correct place
