c_models/reinjector/reinjector.c
spinnman/model/dpri_status.py

fixes: 
fixing the reinjector so that it wont reinject packets that were dumped from going down a link or by a failed processor. Also to add said provenance data items accordingly.  
modules this fix is associated with 
1. SpiNNMan
1. FEC
github markers
tests that need to be done to verify that the change hasnt affected preexisting functionality.
documentation changes
verification of changes from team members

reinjector augmented for link and processor failure dumped packets. 

---

board_test_configuration.py

We can't guarantee that boards are going to be up all the time, so tests that are effectively integration tests need to be resistant to problems caused by the board being absent. This adds a check for whether the board is up to the setup code called in each test that needs an actual board, skipping if the board can't be pinged (itself a proxy for a proper test, but a reasonably simple one).
(This is prompted by `spinn-2` being incidentally down at the moment.)

Double check that test board is reachable!

---

spinnman/transceiver.py

power save turns on machine multiple times.
this log message was used to count the number of times machine was turned on.
So needs to happen even if machine is currently off.

made log message always happen so integration tests can count 

---

spinnman/processes/load_routes_process.py

This change fixed an incorrect number of arguments being supplied to the write_memory_from_bytes() function when called after reset. 
It seems that this is how the arguments used to be supplied, but this file has since been updated. Can you guys verify this fix doesn't go against the latest updates?

Correct number of arguments to write_memory_from_bytes()

---

requirements.txt
setup.py
spinnman/connections/connection_listener.py

Undocumented and (presumably) unsupported classes, even when in the Python core classes, can hide all sorts of problems. Let's use something that *is* supported instead! Alas, core Python only has a supported pool class in 3, but there is a workaround for 2.7 in PyPI.
https://stackoverflow.com/a/11529742/301832
https://docs.python.org/3/library/concurrent.futures.html
https://pypi.org/project/futures/

Use a documented and supported thread pool class

---

board_test_configuration.py

Using a bad *remote* port causes weird effects when the board is in a
strange state. Using a real port is better since then it checks how we'd
route that. (Otherwise, when the board is reachable but otherwise
inaccessible, you get bizarre exceptions from the setup phase of the
tests.)

Use a real port in the board test config

---

spinnman/messages/eieio/command_messages/database_confirmation.py

Fix necessary to make live IO examples work again

Python3 cares about the difference between string and bytestring

---

spinnman/transceiver.py

Makes use of SpiNNakerManchester/SpiNNMachine#81 by asking for unreachable chips to be mapped out.

Remove unreachable chips on machine read

---

spinnman/constants.py
spinnman/transceiver.py

This makes explicit that there is a <tt>user<sub>3</sub></tt> register, and always has been. The slot for user registers in the initialisation structure is 4 words wide. No idea why it wasn't in SpiNNMan, but it should be.

There is a user3 register, and always has been

---

spinnman/exceptions.py
spinnman/processes/abstract_process.py

This is a mechanism for grouping exceptions that occur during the running of a transceiver process (as often the same fault occurs multiple times when it occurs at all).
Recovered from #113

Exception grouping

---

spinnman/messages/scp/impl/flood_fill_data.py

A simple fix to flood fill - retry multiple times.  Note this means that the data is sent multiple times regardless of whether it was received the first time (retry has no check), but this shouldn't be an issue since the same data will be written multiple times to the same place.
This appears to be an issue on large simulations.

Fix flood fill

---

setup.py
spinnman/exceptions.py
spinnman/get_cores_in_run_state.py
spinnman/transceiver.py

Add an exception which is used when cores are detected not to be in a certain state when waiting.  This can then be used in AbstractSpiNNakerBase to give more information after the event.

Fix error cores

---

spinnman/model/chip_summary_info.py
spinnman/processes/get_machine_process.py
spinnman/transceiver.py
unittests/test_transceiver.py

together with https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/493
Only place to specify n_ cores:
machine.MAX_CORES_PER_CHIP
For max machine used to estimate added a config settig
max_machine_core_reduction = 1
For both max machine and use virtual machines
With with_monitors=True (The default)
The result is one less core
So with the default settings:
actually machine 
50% 17 n_user_processors
50% 16 n_user_processors
Max machine
100% 16 n_user_processors
Virtual machine
100% 17 n_user_processors
tested with https://github.com/SpiNNakerManchester/sPyNNaker8/pull/272

Project eighteen

---

.travis.yml
doc/source/index.rst
spinnman/get_cores_in_run_state.py

The big one is that `BoardTestConfiguration` comes from somewhere unknown, which was tripping Sphinx up…

Misc small fixes to the docs

---

spinnman/processes/get_machine_process.py

Python 2.7 uses a string
python 3 a byte array
This works for both.
As this needs a real machine tested by
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/355

fix for pthon 2.7 without breaking 3

---

spinnman/processes/abstract_process.py

Can't use %s any more in logging messages, switching to "... {} .. ".format(..) instead.

Replace %s with {} in formatadapter when logging

---

board_test_configuration.py
quick_tests.py
spinnman/connections/connection_listener.py
spinnman/connections/udp_packet_connections/ip_address_connection.py
spinnman/connections/udp_packet_connections/udp_connection.py
spinnman/get_cores_in_run_state.py
spinnman/processes/get_machine_process.py
spinnman/transceiver.py
spinnman/utilities/utility_functions.py
unittests/test_transceiver.py

Now that we're in Python 3, we can use context managers a good deal more. This simplifies quite a few places, and gives much stronger confidence that the code concerned is correct.

Use Context Managers

---

spinnman/messages/scp/impl/bmp_set_led.py
spinnman/messages/scp/impl/read_adc.py
spinnman/messages/scp/impl/set_led.py
spinnman/processes/de_alloc_sdram_process.py
spinnman/transceiver.py

As shown by https://github.com/SpiNNakerManchester/SpiNNMan/pull/249 and https://github.com/SpiNNakerManchester/IntegrationTests/pull/58
These methods are unused.
In discussion with @lplana and other it was decided best to keep these method and classes.

Deprecate unused methods

---

spinnman/processes/get_machine_process.py

Found by http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/no_inject/7/pipeline
WARNING: Chip 5:2 claimed it has ip address: 239.255.8.128. This ip will not be used.
AttributeError: can't set attribute
Fix. Access the projected variable.

ignore bad ethernet needs to access protected variable

---

spinnman/transceiver.py

The call self._machine.where_is_xy(x, y) failed if it happened before the machine was created.
This fixes and replaces with a best effort string.
Shares its branch name with unrelated other PRs so tested by:
https://github.com/SpiNNakerManchester/IntegrationTests/pull/96

where_is_x_y no longer errors on no machine

---

spinnman/transceiver.py

Solves the issue of discovering a dead board.
Note this version still leave in the 
INFO: No Machine. Root IP:10.11.194.17x:8 y:4
later prs can easily change that.
tested by forcing Spalloc to allocate 2 board job from 10.11.194.17
Also tested one of the spynnaker_integration_tests/test_many_boards which detected the issue with the forced spalloc.

skip possible ethernet if it is not there. IE handle job with hole!

---

spinnman/connections/connection_listener.py
spinnman/connections/udp_packet_connections/udp_connection.py
spinnman/exceptions.py

This makes closed sockets give much less obscure errors too. Complaints about a negative file descriptor are singularly unhelpful (obscure, etc.) whereas saying that a socket is closed is a lot clearer. That in turn helps the connection listener thread behave more sensibly in the situation, which is what clears up a lot of error messages.
That this requires looking at the `_closed` property of sockets is a bit nasty. We could reproduce that ourselves, but that'd just give an opportunity for things to go out of synch.

Stop producing quite so many logging messages during testing

---

spinnman/connections/udp_packet_connections/boot_connection.py
spinnman/transceiver.py

Fixes https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/831
BootPortNum is Always None so can be removed.
Must be doe at the same time as:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/934

removed BootPortNum as always None

---

spinnman/messages/scp/enums/scp_command.py
unittests/scp_tests/test_scp_enums.py

The infrastructure to support `CMD_P2PC` was removed 6 years ago. Nuke the tooling that could try to reach it anyway.

No P2PC command

---

spinnman/processes/application_copy_run_process.py
spinnman/transceiver.py

Fixes the issue that on some boards copy run would re-do the write on 0, 0 (and also sneaks in a fix to the error message by adding an extra \n)

Fix copy run 0 0

---

spinnman/connections/scp_request_pipeline.py
spinnman/exceptions.py
spinnman/messages/scp/abstract_messages/scp_request.py
spinnman/messages/scp/impl/app_copy_run.py

Simple change to allow link to be shown when an error happens, so that it can be checked and blacklisted if needed.  Also removes brackets from an error since the brackets are already included elsewhere (as is the space).

More error details

---

spinnman/connections/scp_request_pipeline.py
spinnman/processes/application_copy_run_process.py

This fixes some of the whole board test errors, by ensuring that during the copy run process, a chip is only visited once!

Fix copy run again

---

spinnman/connections/udp_packet_connections/bmp_connection.py
spinnman/connections/udp_packet_connections/scamp_connection.py
spinnman/connections/udp_packet_connections/udp_connection.py
spinnman/connections/udp_packet_connections/utils.py
spinnman/utilities/socket_utils.py

Add more basic socket utility functions (just wrappers around the basic calls to make the exceptions nicer) and move them to a better location. I leave `update_sdp_header_for_udp_send` where it is because it is used by FEC and is a different kind of utility call; it didn't ever really belong with the others.
Also stop keeping a second copy of the ping code around. SpiNNUtils is to be the expert on that.

More basic network utils

---

spinnman/messages/scp/impl/router_alloc.py
spinnman/messages/scp/impl/sdram_alloc.py
spinnman/messages/scp/impl/sdram_de_alloc.py
spinnman/model/chip_summary_info.py
spinnman/processes/get_machine_process.py

fix new unsupported operand type(s) for | (unsupported-binary-operation)
as well as adds a clear_ethernet_ip_address method so an underscore value does not need to be used.

Pylint fix

---

spinnman/model/cpu_infos.py
spinnman/transceiver.py

Method get_core_status_string does not need to be a transceiver method.
Better in the class it actually use.
Must be done at the same time as:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1076

push get_status_string into cpuinfos

---

spinnman/transceiver.py

clear_router_diagnostic_counters is never called with a none default counter_ids or enables=False
So why do 2 loops to come up with the same 0xFFFFFFFF value every time.

simplify clear_router_diagnostic_counters

---

spinnman/extended/extended_transceiver.py
spinnman/transceiver.py
unittests/test_transceiver.py
unittests/test_version.py

this pr changed the protection single / double under score of some Transceiver methods.
Only methods used outside of the Transceiver and its unittets are without underscore
Support methods used in various places are single underscore
Support methods use exactly once. are double underscore
IE the could be inlined. but are kept separate purely for code readability
removal of bmp_connection is a leftover from https://github.com/SpiNNakerManchester/SpiNNMan/pull/345 where it was moved to ExtendedTransceiver
Tested by
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/extended/3/pipeline/

protect methods

---

spinnman/messages/spinnaker_boot/spinnaker_boot_messages.py
spinnman/transceiver.py

removes params from ensure_board_is_ready that where completely unused.
extra_boot_values kept as @rowleya thinks it may be useful for debugging.
Decided not to move that to ExtendedTransciever as doing so would complicate the code rather than simplify.
So just added a doc to state this is not to send changes based on Board version

remove/ doc ensure_board_is_ready params

---

spinnman/board_test_configuration.py
spinnman/connections/udp_packet_connections/bmp_connection.py
spinnman/extended/extended_transceiver.py
spinnman/model/bmp_connection_data.py
spinnman/spinnman.cfg
spinnman/transceiver.py
spinnman/utilities/utility_functions.py

alternative to https://github.com/SpiNNakerManchester/SpiNNMan/pull/349
That PR would not allow a merge for some weird reason and the spalloc_server test hung
the transceiver code was designed to allow a different BMP per frame and cabinet.
This was however never used. In Frame and cabinet where always 0
This pr removes that.
So a Transceiver now has a single bmp connection and therefor a single bmp conncetion selector
Must be done at the same time as:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1097
https://github.com/SpiNNakerManchester/spalloc_server/pull/90
tested by:
https://github.com/SpiNNakerManchester/IntegrationTests/pull/222

No frames3

---

quick_tests/quick_tests.py
spinnman/board_test_configuration.cfg
spinnman/board_test_configuration.py
spinnman/get_cores_in_run_state.py
unittests/connection_tests/test_udp_connection.py
unittests/model_tests/test_iptag_model.py
unittests/test_transceiver.py

The test board spinn-4.cs.man.ac.uk was down which allowed some bugs to creep in.
This because the test where skipped
Before approving this PR please restart spinn-4.cs.man.ac.uk and rerun the tests
1. BoardTestConfiguration changed from using a cfg file to a trial and error method
- Will try a 4 Chip board first than spinn-4.cs.man.ac.uk and then 192.168.240.1
- (minus) This will make the unit test take longer 45s instead of 19s if all three options are not pingable
- (plus) Automatically uses three different options so more likely to run the tests rather than skipping
- Can still be changed locally but by editing board_test_configuration.py rather than board_test_configuration.cfg
2. BoardTestConfiguration now set cfg Machine/version so unittest_setup() needs to be called first
3. …

Version fix

---

spinnman/spalloc/spalloc_client.py
spinnman/spalloc/spalloc_job.py

Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1112
Database queries have been moved into FEC
open_job_from_database now gets the data read from the database rather than a connection
_write_session_credentials_to_db replaced with get_session_credentials_for_db which just returns the data for the caller to add to the database

Use less transactions

---

spinnman/transceiver.py

move a function that creates and sends a sdp_message to the Transceiver
The only remaining external method that creates an sdp_message and uses the Transceiver to send it.
is:
DataSpeedUpPacketGatherMachineVertex._determine_and_retransmit_missing_seq_nums
which is interesting as every other time that code uses its own connection to send the sdp message
Must be done at the same time as:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1102
Tested by:
https://github.com/SpiNNakerManchester/IntegrationTests/pull/228

move send_chip_update_provenance_and_exit to transciever

---

quick_tests/quick_tests.py
spinnman/transceiver.py
unittests/test_transceiver.py

move the code to make sure the board is on into the transceiver.
This includes power off the board is requested and possible
.ensure_board_is_ready
must be done at the same time as:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1101
tested by:
https://github.com/SpiNNakerManchester/IntegrationTests/pull/227

Power on during init

---

spinnman/model/cpu_info.py
spinnman/model/cpu_infos.py
spinnman/transceiver.py
unittests/model_tests/test_cpu_infos.py

Alternative to https://github.com/SpiNNakerManchester/SpiNNMan/pull/358 et al.
The CPUInfo object contains a lot of data most of which is not actually used.
The objective of this PR is to show what of CPUInfo is actually used so that spin2 does not need to replicate it all.
Reducing what is actually held by CPUInfo and simplify the process to obtain CPUInfo objects is out of scope of this PR.
The conclusion is that the only properties that need to be exposed are x, y, p and state
A few others are used in string outputs but these are only used to debug / understand what is happening so if these string are different for a Spin2 would not be critical.
Therefor this PR.
- Push the creation of status_string into the CPUInfo objects
- removes all methods from CPUInfos that expose CPUInfo …

Hide CPUInfo object

---

spinnman/transceiver.py

While the Transceiver does have a close method it is not designed to be used in the With context
as in with Transceiver(..) as txr:
So I suggested it is no loner declared as a superclass of AbstractContextManager
tested by  https://github.com/SpiNNakerManchester/IntegrationTests/pull/241

Transceiver is never used as a ContextManager

---

spinnman/transceiver/base_transceiver.py
spinnman/transceiver/mockable_transceiver.py
spinnman/transceiver/transceiver.py

In the various merges method send_chip_update_provenance_and_exit was not added to the (Abstract)Tranceiver
Various other methods where not marked with overrides 
docs moved to Abstract class only.
Spellings in docs fixed.

send_chip_update_provenance_and_exit to abstract

---

.pylint_dict.txt
spinnman/messages/scp/impl/app_copy_run.py
spinnman/messages/scp/impl/iptag_get.py
spinnman/messages/scp/impl/write_fpga_register.py
spinnman/model/cpu_info.py
spinnman/model/router_diagnostics.py
spinnman/processes/application_copy_run_process.py
spinnman/processes/get_machine_process.py
spinnman/spalloc/session.py
spinnman/spalloc/spalloc_client.py
spinnman/transceiver/base_transceiver.py
spinnman/transceiver/virtual5Transceiver.py
spinnman/utilities/socket_utils.py

In several cases param names where changed to actual words.
Doc spelling fixes
Adds so spelling ignores
.pylint_dict.txt for words to accept everywhere
- WriteFPGARegister due to SPI and SpI/O
- spinnman/utilities/socket_utils.py due to methods wrapped around

Minor param renaming, doc fixes and ignores for spelling checker

---

spinnman/messages/scp/impl/count_state_response.py

The COUNT request can return a P2P_NOREPLY if not all expected chips replied.  This is not fatal, as a count is still included in the response.  Allowing this to not be a failure here means that:
1. The SpiNNMan SCP pipeline will retry before getting to this point, which means the error might go away.
2. If the pipeline retries continue to lead to P2P_NOREPLY, this code will be called eventually; not failing here means we still have a count, but the count can only be smaller than it should be (as some counts didn't come back before the timeout).
3. The count might still be enough to continue if the chips that didn't reply don't matter.  If not, another mechanism will be used to count the cores anyway (i.e. reading all the CPU statuses separately).  If a chip can't be read there, this will …

Allow no-reply to count message

---

spinnman/model/cpu_infos.py
unittests/model_tests/test_cpu_infos.py

adds and tests a infos_not_in_states method
This because the CpuInfos iter no linger includes CPUInfo items.
needed for:

infos_not_in_states method

---

spinnman/connections/scp_request_pipeline.py
spinnman/processes/abstract_multi_connection_process.py
spinnman/processes/get_n_cores_in_state_process.py
spinnman/processes/send_single_command_process.py

These changes allow the P2P timeout for counting core statuses to get through the rest of the mechanisms.
Tested by: http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/allow_count_p2p_timeout/2/pipeline/

Allow count p2p timeout

---

spinnman/spalloc/spalloc_client.py

This affects proxied spalloc.
So as not what happens in Jenkins not sure we need it.

log job call values

---

unittests/data/test_data.py
unittests/model_tests/test_abstract_process.py
unittests/test_transceiver.py

part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/257

Version and testing for Spin2

---

manual_scripts/get_triad.py
spinnman/spalloc/spalloc_client.py
spinnman/spalloc/spalloc_job.py

The current keep alive cause errors in windows.
This pr simplifies it to use simple threads.
1. A job when creates starts its own keepalive without being asked to
2. The keepalive is a simple thread started by the init
3. The job's destroy method will unset the keepalive url which is the flag for the thread to stop
added a script to get job with a triad.
Must be done at the same time as:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1187
https://github.com/SpiNNakerManchester/sPyNNaker/pull/1453
tested by:
https://github.com/SpiNNakerManchester/microcircuit_model/pull/38
https://github.com/SpiNNakerManchester/IntegrationTests/pull/275

simplify the spalloc keep alive

---

.github/workflows/python_actions.yml
spinnman_integration_tests/__init__.py
spinnman_integration_tests/test_job.py

Similar to https://github.com/SpiNNakerManchester/SpiNNUtils/pull/271
also adds and runs an integration test taken from
https://github.com/SpiNNakerManchester/SpiNNMan/pull/403

Use a complex workflow on Support scripts

---

.github/workflows/python_actions.yml
spinnman/spalloc/spalloc_client.py
spinnman_integration_tests/test_job.py

part of https://github.com/SpiNNakerManchester/sPyNNaker/pull/1455
python_actions.yml updates with more package declarations
Adds 
os.environ["SPALLOC_USER"]
os.environ["SPALLOC_PASSWORD"]

runs an intergation test in linux, windows and macos

---

spinnman/spalloc/spalloc_client.py
spinnman/utilities/locate_connected_machine_ip_address.py

This is potentially useful for reading IO_BUF down a proxy link

Allow getting of an existing job
